AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM Template for suggest-service-queue-batch-handler
Resources:
  QueuePusherFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Timeout: 60
      MemorySize: 128
      CodeUri: .
      Description: >-
        Performs a periodic check of the given site, erroring out on test
        failure.

      Handler: lambda_function.lambda_handler
      EphemeralStorage:
        Size: 512
      Environment:
        Variables:
          DATABASE_URL: "mysql+pymysql://suggest:suggest@host.docker.internal:3306/suggest"
          USER_AGENT: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
          SQS_NAME: "SearchEngineRequestQueue"
          DEBUG_MODE: true
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      Role: arn:aws:iam::203918879438:role/queue-batch-pusher-lambda-role
      Policies:
        - Statement:
            - Action:
                - sqs:*
              Effect: Allow
              Resource: '*'
      RecursiveLoop: Terminate
      SnapStart:
        ApplyOn: None
      Tags:
        lambda-console:blueprint: lambda-canary
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: cron(0/5 * * * ? *)
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto

    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: python3.12-v1_suggest-service-queue-batch-handler